name: Blockhunt
version: ${project.version}
main: gold.tabs.blockhunt.Blockhunt
api-version: 1.16
authors: [ tabsg, wdhg ]
description: A game where you have to hunt for blocks
commands:
  blockhunt:
    description: play blockhunt!
    usage: /blockhunt <rounds>
  blockhunt-overworld:
    description: play blockhunt without needing to enter other dimensions!
    usage: /blockhunt-overworld <rounds>